---
title: "Introduction to infectious disease modelling"
author: by Sebastian Funk, Gwen Knight and Anton Camacho
output:
  html_document:
    toc: false  
---

Welcome to the Modelling Infectious Diseases course at The Institute of Mathematical Sciences, Chennai, India, part of the [Workshop on Infectious Disease Modeling](http://www.imsc.res.in/~sitabhra/meetings/infection15/), 23-28 November, 2015. Below you will find everything that is needed for the lab practical sessions, as well as the slides from our lectures.


## Required software
* [R](http://cran.r-project.org) is used as the main programming language. Please install at least version: R-3.2.0.
* [RStudio](http://www.rstudio.com/products/rstudio/download/) (optional) is a popular graphic user interface (GUI).

## Lab sessions

1. [R Introduction](intro_to_r_gk.html)
2. [Code a stochastic model](code_sto_model.html)
3. [My first fitmodel](my_first_fitmodel.html)

## Lecture Slides

* [An introduction to infectious disease modelling and its applications](intro_modelling_chennai.pdf)
* [Introduction to stochastic modelling](intro_sto_modelling.pdf)
